Advancements:
  enabled: true
BatGrenades:
  enabled: true
BetterArmorStands:
  enabled: true
BlastFurnaces:
  enabled: true
PigTractors:
  enabled: true
Chairs:
  enabled: true
CustomCrafter:
  enabled: true
  StandardCrafting: true
  RecordCrafting: true
  MasterCrafting: true
  BlastFurnace: true
  Disassembler: true
  EquivalentExchange: true
DesireLines:
  enabled: true
  max: 50
  amount: 2
EnderHoppers:
  enabled: true
EndermanSupportClass:
  enabled: true
HeartCanisters:
  enabled: true
InkSpittingSquid:
  enabled: true
LightningRods:
  enabled: true
SoulProbes:
  enabled: true
SpawnerMinecarts:
  enabled: true
SpeedPaths:
  enabled: true
  pathBlock: GRASS_PATH
  speedFactor: 1
TrappedSigns:
  enabled: true
WeightedArmour:
  enabled: true
  level-0: 8
  level-1: 16
  level-2: 20
  weight:
    leather:
      boots: 1
      leggings: 2
      chestplate: 3
      helmet: 1
    chain:
      boots: 1
      leggings: 4
      chestplate: 5
      helmet: 2
    gold:
      boots: 1
      leggings: 3
      chestplate: 5
      helmet: 2
    iron:
      boots: 2
      leggings: 5
      chestplate: 6
      helmet: 2
    diamond:
      boots: 3
      leggings: 6
      chestplate: 8
      helmet: 3
XPStorage:
  enabled: true
ZauberCauldrons:
  enabled: true