Advancements:
  enabled: true
BatGrenades:
  enabled: true
BetterArmorStands:
  enabled: true
BetterFire:
  enabled: true
BlastFurnaces:
  enabled: true
Chairs:
  enabled: true
CustomCrafter:
  enabled: true
  StandardCrafting: true
  RecordCrafting: true
  MasterCrafting: true
  BlastFurnace: true
  Disassembler: true
  EquivalentExchange: true
CustomTerrain:
  enabled: true
  loadRadius: 3
  replacingSpeed: 24576
  CoolerCaves:
    enabled: true
  DangerousDungeons:
    enabled: true
  TowerStructures:
    enabled: true
DesireLines:
  enabled: true
  max: 50
  amount: 2
EnderHoppers:
  enabled: true
EndermanSupportClass:
  enabled: true
HeartCanisters:
  enabled: true
InkSpittingSquid:
  enabled: true
LightningRods:
  enabled: true
PigTractors:
  enabled: true
PotionSwords:
  enabled: true
SoulGlass:
  enabled: true
  smelting:
    cookingTime: 800 #in ticks
    experience: 1
SoulProbes:
  enabled: true
SpawnerMinecarts:
  enabled: true
SpeedPaths:
  enabled: true
  pathBlock: GRASS_PATH
  speedFactor: 2
SunkenTreasure:
  enabled: true
  treasure:
    bone: 15
    seagrass: 15
    squid_spawn: 10
    message_in_a_bottle: 10
    mossy_cobblestone: 10
    kelp: 7.5
    prismarine_crystals: 5
    prismarine_shard: 5
    sea_pickle: 5
    waders: 3
    bottle_o_enchanting: 2.5
    scute: 2.5
    gold_ingot: 2.5
    guardian_spawn: 2.5
    leather_boots: 2.5
    wet_sponge: 1.5
    treasure_chest: .5
  #Override specified values if module Scuba Tanks is enabled
  scubaOverride:
    waders: 2.5
    leather_boots: 2
    scuba_flippers: .5
    scuba_tank: .5
  #Chance of getting treasure for levels of Fortune (I-III)
  chance:
    '0': 0
    '1': 11
    '2': 27
    '3': 49
TrappedSigns:
  enabled: true
UndeadPlayers:
  enabled: true
WeightedArmour:
  enabled: true
  level-0: 8
  level-1: 16
  level-2: 20
  weight:
    leather:
      boots: 1
      leggings: 2
      chestplate: 3
      helmet: 1
    chain:
      boots: 1
      leggings: 4
      chestplate: 5
      helmet: 2
    gold:
      boots: 1
      leggings: 3
      chestplate: 5
      helmet: 2
    iron:
      boots: 2
      leggings: 5
      chestplate: 6
      helmet: 2
    diamond:
      boots: 3
      leggings: 6
      chestplate: 8
      helmet: 3
XpStorage:
  enabled: true
ZauberCauldrons:
  enabled: true
Ziprails:
  enabled: true
  railSpeedFactor: 0.25
