name: Gamemode-4
main: com.belka.spigot.gm4.MainClass
version: 0.2.1
api-version: 1.15
description: Gamemode 4 Plugin
commands:
   gamemode4:
      aliases: gm4
      description: Opens the gm4 settings menu if no sub-command is given.
      usage: /gm4 [reload|version]
