name: Gamemode-4
main: com.belka.spigot.gm4.MainClass
version: 1.2
api-version: 1.13
description: Gamemode 4 Plugin
depend: [CrazyAdvancementsAPI]
commands:
   gamemode4:
      aliases: gm4
      description: Gamemode 4 command.
      usage: /gm4 [sub-command]
