name: Gamemode-4
main: com.belka.spigot.gm4.MainClass
version: 0.1.0
api-version: 1.14
description: Gamemode 4 Plugin
depend: [CrazyAdvancementsAPI, NBTAPI]
commands:
   gamemode4:
      aliases: gm4
      description: Gamemode 4 command.
      usage: /gm4 [sub-command]
